[project]
name = "rvc-beta"
version = "0.1.0"
requires-python = ">=3.12"
description = ""
authors = ["lj1995"]
license = "MIT"
dependencies = [
    "av>=16.0.1",
    "ffmpeg>=1.4",
    "gradio>=5.49.1",
    "numpy>=2.3.4",
    "scikit-learn>=1.7.2",
    "soundfile>=0.13.1",
    "torch>=2.9.0",
]

[[tool.uv.index]]
url = "https://download.pytorch.org/whl/cu130"

[dependency-groups]
dev = ["ruff>=0.14.1"]
