[build-system]
requires = ["setuptools>=68.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "rvc"
version = "0.1.0"
dependencies = [
    "av>=16.0.1",
    "dotenv>=0.9.9",
    "fairseq>=0.12.2",
    "faiss",
    "gradio>=4.44.1",
    "librosa>=0.11.0",
    "praat-parselmouth>=0.4.6",
    "pyworld>=0.3.5",
    "soundfile>=0.13.1",
    "tensorboard>=2.20.0",
    "torch>=2.9.0",
    "torchcrepe>=0.0.24",
]
requires-python = ">=3.13"

[tool.setuptools.packages.find]
where = ["."]
include = ["infer*"]

[[tool.uv.index]]
url = "https://download.pytorch.org/whl/cu130"

[tool.uv.sources]
faiss = { git = "https://github.com/spencersutton/faiss.git" }
fairseq = { git = "https://github.com/yamada-sexta/fairseq.git" }

[tool.ruff.lint]
extend-select = ["I", "UP"]

[tool.pyright]
typeCheckingMode = "strict"
reportMissingParameterType = true
