[project]
name = "rvc-beta"
version = "0.1.0"
requires-python = ">=3.12"
description = ""
license = "MIT"
dependencies = [
    "av>=16.0.1",
    "dotenv>=0.9.9",
    "fairseq>=0.12.2",
    "faiss",
    "faiss-cpu>=1.8.0",
    "ffmpeg-python>=0.2.0",
    "gradio>=5.49.1",
    "librosa>=0.11.0",
    "matplotlib>=3.10.7",
    "numpy>=2.3.4",
    "onnxruntime>=1.23.1",
    "praat-parselmouth>=0.4.6",
    "pyworld>=0.3.5",
    "scikit-learn>=1.7.2",
    "soundfile>=0.13.1",
    "tensorboard>=2.20.0",
    "tensorboardx>=2.6.4",
    "torch>=2.9.0",
    "torchcrepe>=0.0.24",
]

[[tool.uv.index]]
url = "https://download.pytorch.org/whl/cu130"

[tool.uv.sources]
fairseq = { path = "/home/spencer/repos/fairseq" }
faiss = { path = "/home/spencer/repos/faiss/build/faiss/python" }

[tool.ruff]
lint.extend-select = ["I", "PTH", "B", "C4", "G", "LOG", "PIE"]
lint.ignore = ["E722"]

[dependency-groups]
dev = ["ruff>=0.14.1"]
