[project]
name = "rvc-beta"
version = "0.1.0"
requires-python = ">=3.12"
description = ""
authors = ["lj1995"]
license = "MIT"

[[tool.uv.index]]
url = "https://download.pytorch.org/whl/cu130"

[dependency-groups]
dev = [
    "ruff>=0.14.1",
]
