[project]
name = "rvc-beta"
version = "0.1.0"
requires-python = ">=3.12"
description = ""
authors = ["lj1995"]
license = "MIT"
dependencies = [
    "av>=16.0.1",
    "dotenv>=0.9.9",
    "fairseq>=0.12.2",
    "faiss",
    "ffmpeg-python>=0.2.0",
    "gradio>=5.49.1",
    "librosa>=0.11.0",
    "numpy>=2.3.4",
    "praat-parselmouth>=0.4.6",
    "pyworld>=0.3.5",
    "scikit-learn>=1.7.2",
    "soundfile>=0.13.1",
    "torch>=2.9.0",
    "torchcrepe>=0.0.24",
]

[[tool.uv.index]]
url = "https://download.pytorch.org/whl/cu130"

[tool.uv.sources]
faiss = { path = "../repos/faiss/build/faiss/python" }
fairseq = { git = "https://github.com/One-sixth/fairseq.git" }

[tool.ruff]
lint.extend-select = ["I", "PTH", "PL"]

[dependency-groups]
dev = ["ruff>=0.14.1"]
